language: guppy
models:
  # - deepseek/deepseek-chat
  # - deepseek/deepseek-reasoner
  - anthropic/claude-sonnet-4-5
  # - openai/gpt-5-mini
  # - gemini/gemini-3-pro-preview
  # - gemini/gemini-3-flash-preview
n_programs: 2
n_fixing_cycles: 2
max_workers: 10
n_assemble: 10
n_circuits_per_assembly: 1
verbose: true
improve_prompt: false
